hash-format = "sha256"

[[files]]
file = "mods/accessories-tc-layer.pw.toml"
hash = "bd5d617d5a7517e54f375299d0a81179d0be35c83f832564be314da581024bce"
metafile = true

[[files]]
file = "mods/accessories.pw.toml"
hash = "af57e1714dc6207107cb91bac93599e3a7b88cfbcce6763b398692c3fdb20c6d"
metafile = true

[[files]]
file = "mods/aether-1.21.1-1.5.1-neoforge.jar"
hash = "7c315f314d1868bf767243fae5bc0ca7316edeb7b30dfe724096b2f7dd8d1169"

[[files]]
file = "mods/allay-behave-1.3.3+1.21.jar"
hash = "cfddc98ce1cfa1af07adec6b9c8f6b395b271567eef1ee6a378f96cd3e79817f"

[[files]]
file = "mods/alltheleaks.pw.toml"
hash = "8fde22bb3622cf3705ef91079b55bc47185cbb2fc69e8b874807b93a9aea8abf"
metafile = true

[[files]]
file = "mods/applied-energistics-2.pw.toml"
hash = "40463dcf954c6448c8c05df2244d872591a3fa09dd4ffb1e2c349591493c4aba"
metafile = true

[[files]]
file = "mods/applied-mekanistics.pw.toml"
hash = "6809916304466ff7ae4b2efdbdea3c984c06a8d42d24047a4dde9daa87dff82a"
metafile = true

[[files]]
file = "mods/biolith.pw.toml"
hash = "a59d201651a465b098a9c306de4cf049bfe2bec2e1324027a948c089ff40cf39"
metafile = true

[[files]]
file = "mods/cardinal-components-api.pw.toml"
hash = "d23556a37ff83abb1f1bff30fe68991fe93a4e1d301b0c4426747ce417c4a4a6"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "22286fa216349c0767808903a0a38662857d2adee54950a18cbf26c167a06029"
metafile = true

[[files]]
file = "mods/collective.pw.toml"
hash = "c8e5a828790c21fe78de966efc78c2790843780c62436108fc50a109b087b247"
metafile = true

[[files]]
file = "mods/connector-2.0.0-beta.5+1.21.1-full.jar"
hash = "e2d7440117ec3b09686f4ca910dc3338153215eeb8214574553c5744d284b3d5"

[[files]]
file = "mods/connector-extras.pw.toml"
hash = "179ec97bb6d278f2012c725fdfab2c5b00adb529e4f720587ce6c3409aaa572f"
metafile = true

[[files]]
file = "mods/custom-paintings-mod.pw.toml"
hash = "f6dc891a94ec254f220a2db74b6799c76067b86c6079397ca748936015511e70"
metafile = true

[[files]]
file = "mods/ears.pw.toml"
hash = "f77a2399c34ee245fca609dce1f2379a0f7021bc7e4dd42dce7916573ffbc81c"
metafile = true

[[files]]
file = "mods/easy-magic.pw.toml"
hash = "14737f47940556515dfdee992838fb8e19e7145f6aadd565efe04d068d19d75e"
metafile = true

[[files]]
file = "mods/emi.pw.toml"
hash = "8bba135cc6b6a7c70216e312e319016b618ab4e825ec7937ea6107cab637226a"
metafile = true

[[files]]
file = "mods/entity-model-features.pw.toml"
hash = "3a4e194e945214cc457178f48e65b9ab6a8201b6d15b9736cd673324b70b6edd"
metafile = true

[[files]]
file = "mods/entitytexturefeatures.pw.toml"
hash = "65cd00e90de065e99d13352fd5d8aa3bc28d062b9dc935cf1da914a2047b2208"
metafile = true

[[files]]
file = "mods/etherology.pw.toml"
hash = "e26329aaa694d91caac57392307997ef155f79debe0e21a69f227d9d7f963f36"
metafile = true

[[files]]
file = "mods/fabric-shield-lib.pw.toml"
hash = "9e833b976c6cdef5fda71dc446dc2992f9f2d6528b6c3af8aa4375436da4a3aa"
metafile = true

[[files]]
file = "mods/farmers-delight.pw.toml"
hash = "497b906a1005d420251ed82bb438790604b7ed5b17945fefadd0c71e840cb163"
metafile = true

[[files]]
file = "mods/female-gender-neoforge.pw.toml"
hash = "2e2c305b077eb8c92034838afa52ec7f5eb3163f3883258ca0685de7af65e9e6"
metafile = true

[[files]]
file = "mods/ferritecore.pw.toml"
hash = "942b02525962980b6176677cca162d27c1210b686985ad11db0055fe39d42a7d"
metafile = true

[[files]]
file = "mods/forgified-fabric-api-0.107.0+2.0.22+1.21.1.jar"
hash = "ca6f43c7e6fbf8ccab623fb7b28b0ab2287847e13edac311568884e213fcd14d"

[[files]]
file = "mods/forgified-fabric-api.pw.toml"
hash = "91bd23dd592b8587d094b5953eba29ec6529c1828bd3c85cf0ef6786f1be9e3b"
metafile = true

[[files]]
file = "mods/framework.pw.toml"
hash = "159ff6f2ccc1c41ef2f615c804ba8b04aa27c8273ef1845a66bc7a40fdad88e5"
metafile = true

[[files]]
file = "mods/geckolib.pw.toml"
hash = "548cf9b25748105c70af57d4f169f4f8ea9c47c1ec6ec9cae9cbe264bdf31754"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "976a897717e0cab6212b0bf2537a7edadf7e684ea288c178d21290a88e3f517e"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "e2565b5d04fd1157bc97dcac1da9dbd30f2d322be24e2f6ca1f05475ba3aeb18"
metafile = true

[[files]]
file = "mods/macaws-windows.pw.toml"
hash = "e776d14fca80de704085732b1ee05702e9062ad2fa16b5b2a6f3e75096e901e9"
metafile = true

[[files]]
file = "mods/mekanism-generators.pw.toml"
hash = "bbd37762427bd1b7f51cefa138dbcf9eaaa26280a03bc1deb88a155a048a1236"
metafile = true

[[files]]
file = "mods/mekanism-tools.pw.toml"
hash = "3f9d1ecfaa349aa057cf2496b5a5135336209b74ac078ac7806abd4e66da2f78"
metafile = true

[[files]]
file = "mods/mekanism.pw.toml"
hash = "5145c7f731914e9c9e53b7c6833af134bbd6d46e59c7cdcb8a3cab2bb2547d85"
metafile = true

[[files]]
file = "mods/modflared.pw.toml"
hash = "ce3c26021bb85b57b630e6274b1c4ec01d8dc3dcf76c290faf88c31f2eccee74"
metafile = true

[[files]]
file = "mods/noisium.pw.toml"
hash = "c39f473bc613a79aaf8717ced14f9e081451118cd53521ac5d6e6cdd469a3f59"
metafile = true

[[files]]
file = "mods/owo-lib.pw.toml"
hash = "0311ca22213f4a9c8fb943619271944d3ffedf7a17f098e8c0f8fad8f897d700"
metafile = true

[[files]]
file = "mods/particle-rain.pw.toml"
hash = "58e380b4d66907130eaa480252def925457d1033100571c946aaf9179a1e7bde"
metafile = true

[[files]]
file = "mods/plasmo-voice.pw.toml"
hash = "60a101e185cf244c5951a5daa07660b51f213a616a12ea1e6a19f1028a24e311"
metafile = true

[[files]]
file = "mods/puzzles-lib.pw.toml"
hash = "81ae2d56bce436d8e8579a8da32e4c0aa60063f98903bd275f08c8d26d777915"
metafile = true

[[files]]
file = "mods/refurbished-furniture.pw.toml"
hash = "5c77c603cb9ff14bd89d2001df5f90614ceab3f9d02e2bb0ad14e92057698bce"
metafile = true

[[files]]
file = "mods/resourceful-config.pw.toml"
hash = "0d162e18a8010861a674d6cd76780a8298d0a2d11514c8cfb0fd78bdd65a7e68"
metafile = true

[[files]]
file = "mods/selene.pw.toml"
hash = "0993f7e7eec5160e0eeb9253a9f15f228031ec4036aaa39e558922a33a74a161"
metafile = true

[[files]]
file = "mods/sinytra-connector.pw.toml"
hash = "a515d70f1fc773f363dc56670307ebd06e50b0028e6ea1b60649c0bc76b2afcb"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "9050cb92f35f8057726ec547ba3306726a1a4f3b5ed0d147b70d2dc30dcff582"
metafile = true

[[files]]
file = "mods/structure-layout-optimizer.pw.toml"
hash = "943a6e7eb3edc86e87dff02af039208b9af6308ef2185ef905655e6a0538bdd4"
metafile = true

[[files]]
file = "mods/travelers-titles-neoforge.pw.toml"
hash = "45a38f15e6810ff75e3756bc5673fe5cc336099070049699eafaee04f2fae6af"
metafile = true

[[files]]
file = "mods/xaeros-minimap.pw.toml"
hash = "cca27078b7075d2dd7bf5f1a010395c799cf772cdf2a12bf51e94e2d91682c6a"
metafile = true

[[files]]
file = "mods/yungs-api-neoforge.pw.toml"
hash = "1d2251d0958affef0a90edb3acb44250bb5d3bc90539cdf2bbea41ffa28c6ade"
metafile = true

[[files]]
file = "mods/yungs-better-dungeons-neoforge.pw.toml"
hash = "b6527599723cd47781e0e2eb029ba1858ecd000e5d6a972c5497838b6fb967bb"
metafile = true

[[files]]
file = "mods/yungs-better-end-island-neoforge.pw.toml"
hash = "cc41580a5c56304ddb348f65c23baa0bbda2b89a56535a81d045ae49d372eec3"
metafile = true

[[files]]
file = "mods/yungs-better-mineshafts-neoforge.pw.toml"
hash = "c2053af07ae41f932040eaa078a7d22438cbb0bf16ebcf0926740dd8777f9498"
metafile = true

[[files]]
file = "mods/yungs-better-nether-fortresses-neoforge.pw.toml"
hash = "f31730c0959a26773d0f05b9603b30bf43d6872bb7e46f45dff81b90d99547e6"
metafile = true

[[files]]
file = "mods/yungs-better-strongholds-neoforge.pw.toml"
hash = "7a4c5666b0592f4d4ae3ffdb79f365a64fd53cb0de496ae125fb4b88630d32dc"
metafile = true
